# Generated by Django 4.2.16 on 2025-11-03 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Customer name", max_length=255)),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary contact email", max_length=254, unique=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=20
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Company/Organization name",
                        max_length=255,
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact person name",
                        max_length=255,
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Full street address"),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="USA", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Customer status",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about the customer"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked user account after invitation acceptance",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Facility name", max_length=255)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique facility code (auto-generated)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("warehouse", "Warehouse"),
                            ("office", "Office"),
                            ("factory", "Factory"),
                            ("retail", "Retail"),
                            ("datacenter", "Data Center"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        help_text="Type of facility",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Facility description"),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Full street address"),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="USA", max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, help_text="Primary contact name", max_length=255
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, help_text="Primary contact email", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, help_text="Primary contact phone", max_length=20
                    ),
                ),
                (
                    "operational_status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("under_construction", "Under Construction"),
                            ("maintenance", "Maintenance"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="operational",
                        help_text="Current operational status",
                        max_length=50,
                    ),
                ),
                (
                    "square_footage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total square footage",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "year_built",
                    models.IntegerField(
                        blank=True, help_text="Year facility was built", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Internal notes")),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom fields for additional data",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer assigned to this facility",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facilities",
                        to="facilities.customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
                "db_table": "facilities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address for invitation", max_length=254
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Unique invitation token",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Invitation status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Invitation expiration date"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, help_text="When invitation was accepted", null=True
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer being invited",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="facilities.customer",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        help_text="User who sent the invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Invitation",
                "verbose_name_plural": "Customer Invitations",
                "db_table": "customer_invitations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Building name", max_length=255)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Building code (unique within facility)",
                        max_length=50,
                    ),
                ),
                (
                    "building_type",
                    models.CharField(
                        choices=[
                            ("office", "Office"),
                            ("warehouse", "Warehouse"),
                            ("production", "Production"),
                            ("storage", "Storage"),
                            ("laboratory", "Laboratory"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        help_text="Type of building",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Building description"),
                ),
                (
                    "floor_count",
                    models.IntegerField(
                        blank=True, help_text="Number of floors", null=True
                    ),
                ),
                (
                    "square_footage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total square footage",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "construction_year",
                    models.IntegerField(
                        blank=True, help_text="Year building was constructed", null=True
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Building address if different from facility",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, help_text="Building contact name", max_length=255
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, help_text="Building contact email", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, help_text="Building contact phone", max_length=20
                    ),
                ),
                (
                    "operational_status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("under_construction", "Under Construction"),
                            ("maintenance", "Maintenance"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="operational",
                        help_text="Current operational status",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Internal notes")),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom fields for additional data",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer assigned to this building",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="buildings",
                        to="facilities.customer",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        help_text="Parent facility",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildings",
                        to="facilities.facility",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Building",
                "verbose_name_plural": "Buildings",
                "db_table": "buildings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(
                        help_text="ID of the entity this location is attached to"
                    ),
                ),
                ("name", models.CharField(help_text="Location name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Location description"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="Physical address")),
                (
                    "floor",
                    models.CharField(
                        blank=True,
                        help_text="Floor level (e.g., '3rd Floor', 'Basement')",
                        max_length=50,
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True, help_text="Room number or name", max_length=50
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        blank=True, help_text="Zone or area designation", max_length=50
                    ),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional location information",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Type of entity this location is attached to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this location",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "db_table": "locations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="locations_content_646873_idx",
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="locations_latitud_4052bd_idx",
                    ),
                ],
                "unique_together": {("content_type", "object_id")},
            },
        ),
        migrations.AddIndex(
            model_name="facility",
            index=models.Index(fields=["code"], name="facilities_code_af2e81_idx"),
        ),
        migrations.AddIndex(
            model_name="facility",
            index=models.Index(
                fields=["facility_type"], name="facilities_facilit_ab2628_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facility",
            index=models.Index(
                fields=["operational_status"], name="facilities_operati_4b840b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facility",
            index=models.Index(
                fields=["customer"], name="facilities_custome_5c05dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facility",
            index=models.Index(
                fields=["city", "state"], name="facilities_city_87bbc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerinvitation",
            index=models.Index(fields=["email"], name="customer_in_email_3a37d2_idx"),
        ),
        migrations.AddIndex(
            model_name="customerinvitation",
            index=models.Index(fields=["token"], name="customer_in_token_cb7600_idx"),
        ),
        migrations.AddIndex(
            model_name="customerinvitation",
            index=models.Index(fields=["status"], name="customer_in_status_35b20f_idx"),
        ),
        migrations.AddIndex(
            model_name="customerinvitation",
            index=models.Index(
                fields=["expires_at"], name="customer_in_expires_a31d74_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customerinvitation",
            unique_together={("customer", "email")},
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="customers_email_92e882_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["status"], name="customers_status_47bd31_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["company_name"], name="customers_company_c25c85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(
                fields=["facility", "code"], name="buildings_facilit_3f6cb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(
                fields=["building_type"], name="buildings_buildin_043d0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(
                fields=["operational_status"], name="buildings_operati_f1fea5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(
                fields=["customer"], name="buildings_custome_f6fff7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="building",
            unique_together={("facility", "code")},
        ),
    ]
