# Generated by Django 4.2.16 on 2025-11-12 10:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_allow_multiple_visits'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(db_index=True, help_text='Unique request number (e.g., REQ-2025-0001)', max_length=50, unique=True)),
                ('request_type', models.CharField(choices=[('service', 'Service Request'), ('issue', 'Issue Report'), ('maintenance', 'Maintenance Request'), ('inspection', 'Inspection Request')], db_index=True, default='service', help_text='Type of request', max_length=20)),
                ('title', models.CharField(help_text='Brief title of the request', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the request or issue')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', help_text='Priority level', max_length=20)),
                ('issue_type', models.CharField(blank=True, choices=[('breakdown', 'Equipment Breakdown'), ('malfunction', 'Malfunction'), ('safety', 'Safety Concern'), ('performance', 'Performance Issue'), ('other', 'Other')], help_text='Type of issue (for issue reports)', max_length=20, null=True)),
                ('severity', models.CharField(blank=True, choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('critical', 'Critical')], db_index=True, help_text='Severity level (for issue reports)', max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current status of the request', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the request was reviewed', null=True)),
                ('response_message', models.TextField(blank=True, help_text='Response message to customer')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost (not visible to customer)', max_digits=10, null=True)),
                ('estimated_timeline', models.CharField(blank=True, help_text='Estimated timeline for completion', max_length=100)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for admin/manager use only')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the request was last updated')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the request was completed', null=True)),
                ('customer_rating', models.IntegerField(blank=True, help_text='Customer rating (1-5 stars)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('customer_feedback', models.TextField(blank=True, help_text='Customer feedback text')),
                ('feedback_submitted_at', models.DateTimeField(blank=True, help_text='When feedback was submitted', null=True)),
                ('converted_task', models.ForeignKey(blank=True, help_text='Task created from this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='tasks.task')),
                ('customer', models.ForeignKey(help_text='Customer who submitted the request', on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(help_text='Equipment this request is for', on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='equipment.equipment')),
                ('facility', models.ForeignKey(help_text='Facility where equipment is located', on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='facilities.facility')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin/manager who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'db_table': 'service_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_text', models.TextField(help_text='Comment text')),
                ('is_internal', models.BooleanField(db_index=True, default=False, help_text='Whether this is an internal comment (not visible to customer)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the comment was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the comment was last updated')),
                ('request', models.ForeignKey(help_text='Service request this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='service_requests.servicerequest')),
                ('user', models.ForeignKey(blank=True, help_text='User who posted the comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Comment',
                'verbose_name_plural': 'Request Comments',
                'db_table': 'request_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Uploaded file', upload_to='service_requests/%Y/%m/')),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='MIME type', max_length=100)),
                ('is_image', models.BooleanField(db_index=True, default=False, help_text='Whether file is an image')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the file was uploaded')),
                ('request', models.ForeignKey(help_text='Service request this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='service_requests.servicerequest')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Attachment',
                'verbose_name_plural': 'Request Attachments',
                'db_table': 'request_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('created', 'Request Created'), ('reviewed', 'Under Review'), ('accepted', 'Request Accepted'), ('rejected', 'Request Rejected'), ('converted', 'Converted to Task'), ('updated', 'Request Updated'), ('commented', 'Comment Added'), ('completed', 'Request Completed'), ('cancelled', 'Request Cancelled'), ('feedback', 'Feedback Submitted')], db_index=True, help_text='Type of action performed', max_length=20)),
                ('description', models.TextField(help_text='Description of the action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the action')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action was performed')),
                ('request', models.ForeignKey(help_text='Service request this action belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='service_requests.servicerequest')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Action',
                'verbose_name_plural': 'Request Actions',
                'db_table': 'request_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['customer', 'status'], name='service_req_custome_7d484f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['equipment', 'status'], name='service_req_equipme_c7fac0_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['facility', 'status'], name='service_req_facilit_eebed2_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'priority'], name='service_req_status_cf0fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['request_type', 'status'], name='service_req_request_39e408_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['severity', 'status'], name='service_req_severit_29a0e9_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['created_at', 'status'], name='service_req_created_4d71a3_idx'),
        ),
        migrations.AddIndex(
            model_name='requestcomment',
            index=models.Index(fields=['request', 'created_at'], name='request_com_request_7e5d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='requestcomment',
            index=models.Index(fields=['request', 'is_internal'], name='request_com_request_1e8cad_idx'),
        ),
        migrations.AddIndex(
            model_name='requestcomment',
            index=models.Index(fields=['user', 'created_at'], name='request_com_user_id_218f57_idx'),
        ),
        migrations.AddIndex(
            model_name='requestattachment',
            index=models.Index(fields=['request', 'created_at'], name='request_att_request_bedd97_idx'),
        ),
        migrations.AddIndex(
            model_name='requestattachment',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='request_att_uploade_16e45f_idx'),
        ),
        migrations.AddIndex(
            model_name='requestattachment',
            index=models.Index(fields=['is_image'], name='request_att_is_imag_c19fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='requestaction',
            index=models.Index(fields=['request', 'created_at'], name='request_act_request_30b5b7_idx'),
        ),
        migrations.AddIndex(
            model_name='requestaction',
            index=models.Index(fields=['action_type', 'created_at'], name='request_act_action__869810_idx'),
        ),
        migrations.AddIndex(
            model_name='requestaction',
            index=models.Index(fields=['user', 'created_at'], name='request_act_user_id_9a0154_idx'),
        ),
    ]
