# Generated by Django 4.2.16 on 2025-11-10 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("equipment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique task number (auto-generated)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(help_text="Task title", max_length=255)),
                (
                    "description",
                    models.TextField(help_text="Detailed task description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("closed", "Closed"),
                            ("reopened", "Re-Opened"),
                            ("pending", "Pending"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="new",
                        help_text="Administrative status",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="medium",
                        help_text="Task priority",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_start",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Scheduled start date/time",
                        null=True,
                    ),
                ),
                (
                    "scheduled_end",
                    models.DateTimeField(
                        blank=True, help_text="Scheduled end date/time", null=True
                    ),
                ),
                (
                    "is_scheduled",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this task is scheduled for future",
                    ),
                ),
                (
                    "materials_needed",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of materials needed for this task",
                    ),
                ),
                (
                    "materials_received",
                    models.JSONField(
                        blank=True, default=list, help_text="List of materials received"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Internal notes")),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom fields for additional data",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        help_text="Equipment this task is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "db_table": "tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskNumberSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "last_number",
                    models.IntegerField(
                        default=0, help_text="Last generated task number"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Task Number Sequence",
                "verbose_name_plural": "Task Number Sequences",
                "db_table": "task_number_sequence",
            },
        ),
        migrations.CreateModel(
            name="TechnicianTeam",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Team name", max_length=255, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Team description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Whether team is active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        help_text="Team members (technicians only)",
                        limit_choices_to={"role": "technician"},
                        related_name="technician_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Technician Team",
                "verbose_name_plural": "Technician Teams",
                "db_table": "technician_teams",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "work_status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("hold", "Hold"),
                            ("in_progress", "In-Progress"),
                            ("done", "Done"),
                        ],
                        db_index=True,
                        default="open",
                        help_text="Work status (updated by technician)",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        help_text="User who made the assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Individual technician assigned",
                        limit_choices_to={"role": "technician"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Task being assigned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="tasks.task",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team assigned",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignments",
                        to="tasks.technicianteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Assignment",
                "verbose_name_plural": "Task Assignments",
                "db_table": "task_assignments",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.AddIndex(
            model_name="technicianteam",
            index=models.Index(fields=["name"], name="technician__name_1f8639_idx"),
        ),
        migrations.AddIndex(
            model_name="technicianteam",
            index=models.Index(
                fields=["is_active"], name="technician__is_acti_4cb6a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(
                fields=["task", "assignee"], name="task_assign_task_id_e9ff38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(
                fields=["task", "team"], name="task_assign_task_id_c9fab2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(
                fields=["work_status"], name="task_assign_work_st_46057e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(
                fields=["assignee", "work_status"],
                name="task_assign_assigne_6165f2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskassignment",
            unique_together={("task", "assignee"), ("task", "team")},
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["task_number"], name="tasks_task_nu_eff004_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["status", "priority"], name="tasks_status_0fbdac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["equipment", "status"], name="tasks_equipme_d8b491_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["scheduled_start"], name="tasks_schedul_dd4b81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["created_at"], name="tasks_created_db4e37_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["is_scheduled"], name="tasks_is_sche_059954_idx"
            ),
        ),
    ]
