# Generated by Django 4.2.16 on 2025-11-10 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "travel_started_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When technician started traveling to site",
                        null=True,
                    ),
                ),
                (
                    "arrived_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When technician arrived at site",
                        null=True,
                    ),
                ),
                (
                    "departed_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When technician departed from site",
                        null=True,
                    ),
                ),
                (
                    "lunch_started_at",
                    models.DateTimeField(
                        blank=True, help_text="When lunch break started", null=True
                    ),
                ),
                (
                    "lunch_ended_at",
                    models.DateTimeField(
                        blank=True, help_text="When lunch break ended", null=True
                    ),
                ),
                (
                    "equipment_status_at_departure",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("functional", "Functional"),
                            ("shutdown", "Shutdown"),
                        ],
                        help_text="Equipment status when technician departed",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "total_work_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total work hours (arrival to departure minus lunch)",
                        max_digits=5,
                    ),
                ),
                (
                    "normal_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Normal work hours (up to 8 hours)",
                        max_digits=5,
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Overtime hours (beyond 8 hours)",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Task being worked on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to="tasks.task",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        help_text="Technician performing the work",
                        limit_choices_to={"role": "technician"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Log",
                "verbose_name_plural": "Time Logs",
                "db_table": "time_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "technician"],
                        name="time_logs_task_id_018882_idx",
                    ),
                    models.Index(
                        fields=["technician", "departed_at"],
                        name="time_logs_technic_39a729_idx",
                    ),
                    models.Index(
                        fields=["arrived_at", "departed_at"],
                        name="time_logs_arrived_6f0715_idx",
                    ),
                    models.Index(
                        fields=["travel_started_at"],
                        name="time_logs_travel__b769b8_idx",
                    ),
                ],
                "unique_together": {("task", "technician")},
            },
        ),
    ]
