# Generated by Django 4.2.16 on 2025-11-10 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0002_timelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("status_changed", "Status Changed"),
                            ("priority_changed", "Priority Changed"),
                            ("assigned", "Assigned"),
                            ("work_status_changed", "Work Status Changed"),
                            ("comment_added", "Comment Added"),
                            ("file_uploaded", "File Uploaded"),
                            ("travel_started", "Travel Started"),
                            ("arrived", "Arrived"),
                            ("departed", "Departed"),
                            ("lunch_started", "Lunch Started"),
                            ("lunch_ended", "Lunch Ended"),
                            ("material_needed", "Material Needed"),
                            ("material_received", "Material Received"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True,
                        help_text="Field that was changed (if applicable)",
                        max_length=100,
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, help_text="Previous value (if applicable)"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, help_text="New value (if applicable)"),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context and details",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Task this history entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task History",
                "verbose_name_plural": "Task History",
                "db_table": "task_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "created_at"],
                        name="task_histor_task_id_fb95a0_idx",
                    ),
                    models.Index(
                        fields=["action"], name="task_histor_action_9f78fc_idx"
                    ),
                    models.Index(
                        fields=["user"], name="task_histor_user_id_7041ef_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="task_histor_created_89d443_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comment", models.TextField(help_text="Comment text")),
                (
                    "is_system_generated",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this is an automatic system comment",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who wrote the comment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Task this comment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Comment",
                "verbose_name_plural": "Task Comments",
                "db_table": "task_comments",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "created_at"],
                        name="task_commen_task_id_413a08_idx",
                    ),
                    models.Index(
                        fields=["author"], name="task_commen_author__dbe0d1_idx"
                    ),
                    models.Index(
                        fields=["is_system_generated"],
                        name="task_commen_is_syst_6c6a5c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded file", upload_to="task_attachments/%Y/%m/"
                    ),
                ),
                (
                    "filename",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                ("file_type", models.CharField(help_text="MIME type", max_length=100)),
                (
                    "is_image",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether file is an image",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Task this attachment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tasks.task",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded the file",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Attachment",
                "verbose_name_plural": "Task Attachments",
                "db_table": "task_attachments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "created_at"],
                        name="task_attach_task_id_3cbf49_idx",
                    ),
                    models.Index(
                        fields=["uploaded_by"], name="task_attach_uploade_02cb7c_idx"
                    ),
                    models.Index(
                        fields=["is_image"], name="task_attach_is_imag_ad185d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MaterialLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[("needed", "Needed"), ("received", "Received")],
                        db_index=True,
                        help_text="Whether material is needed or received",
                        max_length=20,
                    ),
                ),
                (
                    "material_name",
                    models.CharField(help_text="Name of the material", max_length=255),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity of material",
                        max_digits=10,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit of measurement (e.g., pieces, kg, liters)",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the material"
                    ),
                ),
                ("logged_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "logged_by",
                    models.ForeignKey(
                        help_text="User who logged the material",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Task this material log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_logs",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Log",
                "verbose_name_plural": "Material Logs",
                "db_table": "material_logs",
                "ordering": ["-logged_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "log_type"],
                        name="material_lo_task_id_ad4153_idx",
                    ),
                    models.Index(
                        fields=["log_type"], name="material_lo_log_typ_dfdc9c_idx"
                    ),
                    models.Index(
                        fields=["logged_at"], name="material_lo_logged__f61a6a_idx"
                    ),
                ],
            },
        ),
    ]
