# Generated by Django 4.2.16 on 2025-11-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_taskhistory_taskcomment_taskattachment_materiallog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelog",
            name="normal_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Normal work hours (up to 8 hours)",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="timelog",
            name="overtime_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Overtime hours (beyond 8 hours)",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="timelog",
            name="total_work_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total work hours (arrival to departure minus lunch)",
                max_digits=8,
            ),
        ),
    ]
