# Generated by Django 4.2.16 on 2025-11-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_increase_work_hours_digits"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timelog",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["task", "technician", "departed_at"],
                name="time_logs_task_id_5309d1_idx",
            ),
        ),
    ]
