# Generated by Django 4.2.16 on 2025-12-19 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0005_allow_multiple_visits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskassignment",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                help_text="Individual technician assigned",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="technicianteam",
            name="members",
            field=models.ManyToManyField(
                help_text="Team members (technicians only)",
                related_name="technician_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="timelog",
            name="technician",
            field=models.ForeignKey(
                help_text="Technician performing the work",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
