# Generated by Django 4.2.16 on 2025-12-25 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_refactor_task_attachment_to_use_userfile"),
        ("tasks", "0007_task_due_date_task_tasks_due_dat_0359a9_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="taskattachment",
            name="task_attach_uploade_02cb7c_idx",
        ),
        migrations.RemoveIndex(
            model_name="taskattachment",
            name="task_attach_is_imag_ad185d_idx",
        ),
        migrations.AddField(
            model_name="taskattachment",
            name="user_file",
            field=models.OneToOneField(
                blank=True,
                help_text="UserFile record for this attachment",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_attachment",
                to="files.userfile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskattachment",
            unique_together={("task", "user_file")},
        ),
        migrations.AddIndex(
            model_name="taskattachment",
            index=models.Index(
                fields=["user_file"], name="task_attach_user_fi_33b96f_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="taskattachment",
            name="file",
        ),
        migrations.RemoveField(
            model_name="taskattachment",
            name="file_size",
        ),
        migrations.RemoveField(
            model_name="taskattachment",
            name="file_type",
        ),
        migrations.RemoveField(
            model_name="taskattachment",
            name="filename",
        ),
        migrations.RemoveField(
            model_name="taskattachment",
            name="is_image",
        ),
        migrations.RemoveField(
            model_name="taskattachment",
            name="uploaded_by",
        ),
    ]
