# Generated by Django 4.2.16 on 2026-01-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0008_refactor_task_attachment_to_use_userfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("on_hold", "On Hold"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="open",
                help_text="Work status of the task",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["work_status"], name="tasks_work_st_d8824c_idx"),
        ),
    ]
