# Generated by Django 4.2.16 on 2026-01-15 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0009_task_work_status_task_tasks_work_st_d8824c_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="taskassignment",
            name="task_assign_work_st_46057e_idx",
        ),
        migrations.RemoveIndex(
            model_name="taskassignment",
            name="task_assign_assigne_6165f2_idx",
        ),
        migrations.RemoveField(
            model_name="taskassignment",
            name="work_status",
        ),
    ]
