# Generated by Django 4.2.16 on 2025-11-30 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_add_billing_cycle"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="subscription",
            new_name="billing_sub_stripe__f2f5cc_idx",
            old_name="billing_sub_stripe_c_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="billing_sub_stripe__4b5970_idx",
            old_name="billing_sub_stripe_s_idx",
        ),
    ]
