# Generated by Django 4.2.16 on 2025-11-03 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("facilities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentNumberSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "last_number",
                    models.IntegerField(
                        default=0, help_text="Last generated equipment number"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Equipment Number Sequence",
                "verbose_name_plural": "Equipment Number Sequences",
                "db_table": "equipment_number_sequence",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "equipment_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique equipment number (auto-generated)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Equipment name", max_length=255)),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("hvac", "HVAC"),
                            ("electrical", "Electrical"),
                            ("plumbing", "Plumbing"),
                            ("machinery", "Machinery"),
                            ("it", "IT Equipment"),
                            ("safety", "Safety Equipment"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        help_text="Type of equipment",
                        max_length=50,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, help_text="Equipment manufacturer", max_length=255
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, help_text="Equipment model", max_length=255
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Manufacturer serial number",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Equipment description"),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, help_text="Date of purchase", null=True
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Purchase price",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "warranty_expiration",
                    models.DateField(
                        blank=True, help_text="Warranty expiration date", null=True
                    ),
                ),
                (
                    "installation_date",
                    models.DateField(
                        blank=True, help_text="Installation date", null=True
                    ),
                ),
                (
                    "operational_status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("maintenance", "Maintenance"),
                            ("broken", "Broken"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="operational",
                        help_text="Current operational status",
                        max_length=50,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        default="good",
                        help_text="Physical condition",
                        max_length=50,
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True, default=dict, help_text="Technical specifications"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Internal notes")),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom fields for additional data",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        help_text="Parent building",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_items",
                        to="facilities.building",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer assigned to this equipment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_items",
                        to="facilities.customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment",
                "verbose_name_plural": "Equipment",
                "db_table": "equipment",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["equipment_number"], name="equipment_equipme_786e70_idx"
                    ),
                    models.Index(
                        fields=["building"], name="equipment_buildin_58dedc_idx"
                    ),
                    models.Index(
                        fields=["equipment_type"], name="equipment_equipme_f4cc15_idx"
                    ),
                    models.Index(
                        fields=["manufacturer"], name="equipment_manufac_db37d0_idx"
                    ),
                    models.Index(
                        fields=["operational_status"],
                        name="equipment_operati_f2bd4a_idx",
                    ),
                    models.Index(
                        fields=["customer"], name="equipment_custome_d3f00b_idx"
                    ),
                ],
            },
        ),
    ]
