# Generated by Django 4.2.16 on 2025-11-06 15:11

from django.db import migrations, models
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_tenantinvitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="schema_name",
            field=models.CharField(
                db_index=True,
                max_length=63,
                unique=True,
                validators=[django_tenants.postgresql_backend.base._check_schema_name],
            ),
        ),
    ]
