# Generated by Django 4.2.16 on 2025-11-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0004_alter_tenant_schema_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="domain",
            field=models.CharField(db_index=True, max_length=253, unique=True),
        ),
    ]
