# Generated by Django 4.2.16 on 2025-11-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0007_migrate_user_roles_to_tenant_members"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tenantmember",
            new_name="tenant_memb_tenant__2b89ce_idx",
            old_name="tenant_memb_tenant__idx",
        ),
        migrations.RenameIndex(
            model_name="tenantmember",
            new_name="tenant_memb_role_b300d5_idx",
            old_name="tenant_memb_role_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantmember",
            new_name="tenant_memb_employe_643bb9_idx",
            old_name="tenant_memb_employe_idx",
        ),
        migrations.AlterField(
            model_name="tenant",
            name="company_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1-10", "1-10 employees"),
                    ("11-50", "11-50 employees"),
                    ("51-200", "51-200 employees"),
                    ("201-500", "201-500 employees"),
                    ("500+", "500+ employees"),
                ],
                max_length=50,
            ),
        ),
    ]
