# Generated by Django 4.2.16 on 2025-11-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tenants",
            "0008_rename_tenant_memb_tenant__idx_tenant_memb_tenant__2b89ce_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantmember",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
