# Generated by Django 4.2.16 on 2025-12-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0009_tenantmember_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="currency",
            field=models.CharField(
                default="USD",
                help_text="Currency code (ISO 4217, e.g., USD, EUR, GBP)",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="default_normal_hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="Default hourly rate for normal hours (in tenant's currency)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="default_overtime_hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=75.0,
                help_text="Default hourly rate for overtime hours (in tenant's currency)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="normal_working_hours_per_day",
            field=models.DecimalField(
                decimal_places=2,
                default=8.0,
                help_text="Normal working hours per day (e.g., 8.00 for 8 hours)",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="overtime_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=1.5,
                help_text="Overtime rate multiplier (e.g., 1.5 for time-and-a-half)",
                max_digits=4,
            ),
        ),
    ]
