# Generated by Django 4.2.16 on 2025-12-02 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0010_tenantsettings_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicianWageRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "normal_hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hourly rate for normal hours",
                        max_digits=10,
                    ),
                ),
                (
                    "overtime_hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hourly rate for overtime hours",
                        max_digits=10,
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        db_index=True, help_text="Date when this rate becomes effective"
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Date when this rate expires (null = current rate)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this rate is currently active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this rate change"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this rate",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wage_rates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        help_text="Technician this rate applies to",
                        limit_choices_to={"role": "technician"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wage_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Technician Wage Rate",
                "verbose_name_plural": "Technician Wage Rates",
                "db_table": "technician_wage_rates",
                "ordering": ["-effective_from", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["technician", "effective_from"],
                        name="technician__technic_f855a6_idx",
                    ),
                    models.Index(
                        fields=["technician", "is_active"],
                        name="technician__technic_cf6a6f_idx",
                    ),
                    models.Index(
                        fields=["effective_from", "effective_to"],
                        name="technician__effecti_055880_idx",
                    ),
                ],
            },
        ),
    ]
