# Generated by Django 4.2.16 on 2025-12-02 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0011_technicianwagerate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technicianwagerate",
            name="technician",
            field=models.ForeignKey(
                help_text="Technician this rate applies to (role validated via TenantMember)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wage_rates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
