"""
Excel Report Exporter

Copyright (c) 2025 FieldPilot. All rights reserved.
This source code is proprietary and confidential.
"""
import logging
from io import BytesIO
from datetime import datetime, date
from decimal import Decimal

logger = logging.getLogger(__name__)


class ExcelExporter:
    """
    Generate Excel reports using openpyxl.
    """
    
    def __init__(self, data, report_config):
        """
        Initialize Excel exporter.
        
        Args:
            data: Report data dictionary
            report_config: Configuration for Excel generation
        """
        self.data = data
        self.config = report_config
    
    def generate(self):
        """
        Generate Excel workbook and return bytes.
        
        Returns:
            bytes: Excel file content
        """
        try:
            from openpyxl import Workbook
            from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
            from openpyxl.utils import get_column_letter
            
            # Create workbook
            wb = Workbook()
            
            # Remove default sheet
            if 'Sheet' in wb.sheetnames:
                wb.remove(wb['Sheet'])
            
            # Create summary sheet
            self._create_summary_sheet(wb)
            
            # Create data sheets based on report type
            report_type = self.data.get('report_type', 'unknown')
            
            if report_type in ['task_summary', 'equipment_summary', 'service_request_summary']:
                self._create_summary_data_sheets(wb)
            elif report_type in ['task_detail', 'equipment_detail', 'service_request_detail']:
                self._create_detail_data_sheets(wb)
            elif report_type == 'technician_worksheet':
                self._create_worksheet_sheets(wb)
            elif report_type in ['technician_performance', 'technician_productivity']:
                self._create_performance_sheets(wb)
            elif report_type == 'labor_cost':
                self._create_labor_cost_sheets(wb)
            elif report_type == 'materials_usage':
                self._create_materials_sheets(wb)
            elif report_type == 'customer_billing':
                self._create_billing_sheets(wb)
            else:
                # Generic data sheet
                self._create_generic_data_sheet(wb)
            
            # Save to bytes
            buffer = BytesIO()
            wb.save(buffer)
            buffer.seek(0)
            
            logger.info(f"Excel generated successfully for report type: {report_type}")
            return buffer.getvalue()
            
        except ImportError as e:
            logger.error(f"openpyxl not installed: {str(e)}")
            raise ImportError(
                "openpyxl is required for Excel generation. "
                "Install it with: pip install openpyxl"
            )
        except Exception as e:
            logger.error(f"Error generating Excel: {str(e)}", exc_info=True)
            raise
    
    def _create_summary_sheet(self, wb):
        """Create summary sheet with report metadata."""
        from openpyxl.styles import Font, PatternFill, Alignment
        
        ws = wb.create_sheet("Summary", 0)
        
        # Title
        ws['A1'] = self.data.get('report_name', 'Report')
        ws['A1'].font = Font(size=16, bold=True)
        
        # Metadata
        row = 3
        ws[f'A{row}'] = 'Generated At:'
        ws[f'B{row}'] = self.data.get('generated_at', '')
        row += 1
        
        ws[f'A{row}'] = 'Generated By:'
        ws[f'B{row}'] = self.data.get('generated_by', {}).get('name', '')
        row += 1
        
        # Filters
        if self.data.get('filters'):
            row += 1
            ws[f'A{row}'] = 'Filters:'
            ws[f'A{row}'].font = Font(bold=True)
            row += 1
            
            for key, value in self.data.get('filters', {}).items():
                ws[f'A{row}'] = f"  {key}:"
                ws[f'B{row}'] = str(value)
                row += 1
        
        # Auto-size columns
        ws.column_dimensions['A'].width = 20
        ws.column_dimensions['B'].width = 40
    
    def _create_summary_data_sheets(self, wb):
        """Create sheets for summary reports."""
        from openpyxl.styles import Font, PatternFill
        
        data = self.data.get('data', {})
        
        # Summary metrics sheet
        if 'summary' in data:
            ws = wb.create_sheet("Metrics")
            self._write_dict_to_sheet(ws, data['summary'], "Summary Metrics")
        
        # Breakdown sheets
        if 'by_status' in data:
            ws = wb.create_sheet("By Status")
            self._write_breakdown_to_sheet(ws, data['by_status'], "Status", "Count")
        
        if 'by_priority' in data:
            ws = wb.create_sheet("By Priority")
            self._write_breakdown_to_sheet(ws, data['by_priority'], "Priority", "Count")
        
        if 'by_type' in data:
            ws = wb.create_sheet("By Type")
            self._write_breakdown_to_sheet(ws, data['by_type'], "Type", "Count")
    
    def _create_detail_data_sheets(self, wb):
        """Create sheets for detail reports."""
        data = self.data.get('data', {})
        
        # Get the main data list
        items = None
        if 'tasks' in data:
            items = data['tasks']
            sheet_name = "Tasks"
        elif 'equipment' in data:
            items = data['equipment']
            sheet_name = "Equipment"
        elif 'requests' in data:
            items = data['requests']
            sheet_name = "Requests"
        
        if items:
            ws = wb.create_sheet(sheet_name)
            self._write_list_to_sheet(ws, items)
    
    def _create_worksheet_sheets(self, wb):
        """Create sheets for technician worksheets."""
        data = self.data.get('data', {})
        worksheets = data.get('worksheets', [])
        
        for worksheet in worksheets:
            tech_name = worksheet.get('technician', {}).get('name', 'Unknown')
            ws = wb.create_sheet(tech_name[:31])  # Excel sheet name limit
            
            # Write technician info
            ws['A1'] = 'Technician:'
            ws['B1'] = tech_name
            ws['A2'] = 'Total Hours:'
            ws['B2'] = worksheet.get('totals', {}).get('total_work_hours', 0)
            
            # Write time logs
            self._write_list_to_sheet(ws, worksheet.get('time_logs', []), start_row=4)
    
    def _create_performance_sheets(self, wb):
        """Create sheets for performance reports."""
        data = self.data.get('data', {})
        
        if 'performance' in data:
            ws = wb.create_sheet("Performance")
            self._write_list_to_sheet(ws, data['performance'])
        
        if 'productivity' in data:
            ws = wb.create_sheet("Productivity")
            self._write_list_to_sheet(ws, data['productivity'])
    
    def _create_labor_cost_sheets(self, wb):
        """Create sheets for labor cost reports."""
        data = self.data.get('data', {})
        
        if 'by_technician' in data:
            ws = wb.create_sheet("By Technician")
            self._write_list_to_sheet(ws, data['by_technician'])
        
        if 'by_task' in data:
            ws = wb.create_sheet("By Task")
            self._write_list_to_sheet(ws, data['by_task'])
        
        if 'by_customer' in data:
            ws = wb.create_sheet("By Customer")
            self._write_list_to_sheet(ws, data['by_customer'])
    
    def _create_materials_sheets(self, wb):
        """Create sheets for materials reports."""
        data = self.data.get('data', {})
        
        if 'material_summary' in data:
            ws = wb.create_sheet("Material Summary")
            self._write_list_to_sheet(ws, data['material_summary'])
        
        if 'by_task' in data:
            ws = wb.create_sheet("By Task")
            # Flatten the nested structure
            flattened = []
            for task_data in data['by_task']:
                task_info = task_data.get('task', {})
                for material in task_data.get('materials_needed', []):
                    flattened.append({
                        'task_number': task_info.get('task_number'),
                        'type': 'Needed',
                        **material
                    })
                for material in task_data.get('materials_received', []):
                    flattened.append({
                        'task_number': task_info.get('task_number'),
                        'type': 'Received',
                        **material
                    })
            self._write_list_to_sheet(ws, flattened)
    
    def _create_billing_sheets(self, wb):
        """Create sheets for billing reports."""
        data = self.data.get('data', {})
        
        if 'billing_by_customer' in data:
            ws = wb.create_sheet("Customer Billing")
            # Flatten nested structure
            flattened = []
            for billing in data['billing_by_customer']:
                customer = billing.get('customer', {})
                labor = billing.get('labor', {})
                flattened.append({
                    'company_name': customer.get('company_name'),
                    'contact_name': customer.get('contact_name'),
                    'total_hours': labor.get('total_hours'),
                    'labor_cost': labor.get('labor_cost'),
                    'total_billable': billing.get('total_billable'),
                    'total_tasks': billing.get('total_tasks'),
                })
            self._write_list_to_sheet(ws, flattened)
    
    def _create_generic_data_sheet(self, wb):
        """Create generic data sheet for unknown report types."""
        ws = wb.create_sheet("Data")
        data = self.data.get('data', {})
        self._write_dict_to_sheet(ws, data, "Report Data")
    
    def _write_dict_to_sheet(self, ws, data_dict, title=None):
        """Write dictionary to sheet as key-value pairs."""
        from openpyxl.styles import Font
        
        row = 1
        if title:
            ws[f'A{row}'] = title
            ws[f'A{row}'].font = Font(size=14, bold=True)
            row += 2
        
        for key, value in data_dict.items():
            ws[f'A{row}'] = str(key).replace('_', ' ').title()
            ws[f'B{row}'] = self._format_value(value)
            row += 1
        
        ws.column_dimensions['A'].width = 30
        ws.column_dimensions['B'].width = 20
    
    def _write_breakdown_to_sheet(self, ws, data_dict, col1_name, col2_name):
        """Write breakdown data to sheet."""
        from openpyxl.styles import Font, PatternFill
        
        # Headers
        ws['A1'] = col1_name
        ws['B1'] = col2_name
        ws['A1'].font = Font(bold=True)
        ws['B1'].font = Font(bold=True)
        ws['A1'].fill = PatternFill(start_color="CCCCCC", end_color="CCCCCC", fill_type="solid")
        ws['B1'].fill = PatternFill(start_color="CCCCCC", end_color="CCCCCC", fill_type="solid")
        
        # Data
        row = 2
        for key, value in data_dict.items():
            ws[f'A{row}'] = str(key).title()
            ws[f'B{row}'] = value
            row += 1
        
        ws.column_dimensions['A'].width = 20
        ws.column_dimensions['B'].width = 15
    
    def _write_list_to_sheet(self, ws, data_list, start_row=1):
        """Write list of dictionaries to sheet as table."""
        from openpyxl.styles import Font, PatternFill
        
        if not data_list:
            ws['A1'] = 'No data available'
            return
        
        # Get headers from first item
        headers = self._flatten_dict_keys(data_list[0])
        
        # Write headers
        for col_idx, header in enumerate(headers, 1):
            cell = ws.cell(row=start_row, column=col_idx)
            cell.value = str(header).replace('_', ' ').title()
            cell.font = Font(bold=True)
            cell.fill = PatternFill(start_color="CCCCCC", end_color="CCCCCC", fill_type="solid")
        
        # Write data
        for row_idx, item in enumerate(data_list, start_row + 1):
            flattened = self._flatten_dict(item)
            for col_idx, header in enumerate(headers, 1):
                value = flattened.get(header, '')
                ws.cell(row=row_idx, column=col_idx).value = self._format_value(value)
        
        # Auto-size columns
        for col_idx in range(1, len(headers) + 1):
            ws.column_dimensions[self._get_column_letter(col_idx)].width = 15
    
    def _flatten_dict(self, d, parent_key='', sep='_'):
        """Flatten nested dictionary."""
        items = []
        for k, v in d.items():
            new_key = f"{parent_key}{sep}{k}" if parent_key else k
            if isinstance(v, dict):
                items.extend(self._flatten_dict(v, new_key, sep=sep).items())
            else:
                items.append((new_key, v))
        return dict(items)
    
    def _flatten_dict_keys(self, d, parent_key='', sep='_'):
        """Get flattened dictionary keys."""
        return list(self._flatten_dict(d, parent_key, sep).keys())
    
    def _format_value(self, value):
        """Format value for Excel cell."""
        if isinstance(value, (datetime, date)):
            return value.isoformat()
        elif isinstance(value, Decimal):
            return float(value)
        elif isinstance(value, (list, dict)):
            return str(value)
        elif value is None:
            return ''
        return value
    
    def _get_column_letter(self, col_idx):
        """Get Excel column letter from index."""
        from openpyxl.utils import get_column_letter
        return get_column_letter(col_idx)


def generate_excel_report(report_data, report_type):
    """
    Convenience function to generate Excel from report data.
    
    Args:
        report_data: Report data dictionary
        report_type: Type of report
        
    Returns:
        bytes: Excel file content
    """
    config = {
        'report_type': report_type,
    }
    
    exporter = ExcelExporter(report_data, config)
    return exporter.generate()
