# Generated by Django 4.2.16 on 2025-11-14 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Schedule name", max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of report to generate",
                        max_length=100,
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filters to apply to the report",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel")],
                        default="pdf",
                        help_text="Report output format",
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        help_text="How often to generate the report",
                        max_length=20,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        help_text="Day of week for weekly schedules (0=Monday, 6=Sunday)",
                        null=True,
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True,
                        help_text="Day of month for monthly schedules (1-31)",
                        null=True,
                    ),
                ),
                (
                    "time_of_day",
                    models.TimeField(help_text="Time of day to generate the report"),
                ),
                (
                    "recipients",
                    models.JSONField(
                        default=list,
                        help_text="List of email addresses to send the report to",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this schedule is active",
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, help_text="When the schedule last ran", null=True
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When the schedule will run next",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Schedule",
                "verbose_name_plural": "Report Schedules",
                "db_table": "report_schedules",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "next_run"],
                        name="report_sche_is_acti_dd723c_idx",
                    ),
                    models.Index(
                        fields=["report_type"], name="report_sche_report__a2c5ad_idx"
                    ),
                    models.Index(
                        fields=["frequency"], name="report_sche_frequen_825450_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of report generated",
                        max_length=100,
                    ),
                ),
                (
                    "report_name",
                    models.CharField(
                        help_text="Human-readable report name", max_length=255
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filters applied to the report",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("json", "JSON"), ("pdf", "PDF"), ("excel", "Excel")],
                        db_index=True,
                        default="json",
                        help_text="Report output format",
                        max_length=20,
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the report was generated",
                    ),
                ),
                (
                    "execution_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Execution time in seconds",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Report generation status",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if generation failed"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, help_text="Path to generated file", max_length=500
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who generated the report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Audit Log",
                "verbose_name_plural": "Report Audit Logs",
                "db_table": "report_audit_logs",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "generated_at"],
                        name="report_audi_user_id_ec9519_idx",
                    ),
                    models.Index(
                        fields=["report_type", "generated_at"],
                        name="report_audi_report__a825d5_idx",
                    ),
                    models.Index(
                        fields=["status"], name="report_audi_status_10eab9_idx"
                    ),
                    models.Index(
                        fields=["format"], name="report_audi_format_592aed_idx"
                    ),
                ],
            },
        ),
    ]
