# Generated by Django 4.2.16 on 2025-11-30 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_remove_role_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="authenticat_role_7fb088_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="authenticat_employe_00f71a_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
    ]
