# Generated by Django 4.2.16 on 2025-12-19 14:03

import apps.files.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tasks", "0006_alter_taskassignment_assignee_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_requests", "0001_initial_service_requests"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFile",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded file",
                        max_length=500,
                        upload_to=apps.files.models.user_file_upload_path,
                    ),
                ),
                (
                    "filename",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "file_type",
                    models.CharField(help_text="MIME type of the file", max_length=100),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for the file",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Tags for organizing files"
                    ),
                ),
                (
                    "is_image",
                    models.BooleanField(
                        default=False, help_text="Whether file is an image"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Whether file is publicly accessible"
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional service request attachment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_files",
                        to="service_requests.servicerequest",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional task attachment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_files",
                        to="tasks.task",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded the file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User File",
                "verbose_name_plural": "User Files",
                "db_table": "user_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileShare",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "can_download",
                    models.BooleanField(
                        default=True, help_text="Whether recipient can download"
                    ),
                ),
                (
                    "can_edit",
                    models.BooleanField(
                        default=False, help_text="Whether recipient can edit metadata"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When share link expires", null=True
                    ),
                ),
                (
                    "share_token",
                    models.CharField(
                        blank=True,
                        help_text="Token for public share links",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "access_count",
                    models.IntegerField(
                        default=0, help_text="Number of times accessed"
                    ),
                ),
                (
                    "last_accessed_at",
                    models.DateTimeField(
                        blank=True, help_text="Last access time", null=True
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        help_text="File being shared",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="files.userfile",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        help_text="User who shared the file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        blank=True,
                        help_text="User file is shared with (null for public links)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "File Share",
                "verbose_name_plural": "File Shares",
                "db_table": "file_shares",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="userfile",
            index=models.Index(
                fields=["uploaded_by", "-created_at"],
                name="user_files_uploade_91ecbb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userfile",
            index=models.Index(fields=["task"], name="user_files_task_id_195325_idx"),
        ),
        migrations.AddIndex(
            model_name="userfile",
            index=models.Index(
                fields=["service_request"], name="user_files_service_b077e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userfile",
            index=models.Index(
                fields=["file_type"], name="user_files_file_ty_37ec1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userfile",
            index=models.Index(
                fields=["is_image"], name="user_files_is_imag_9f4c05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileshare",
            index=models.Index(
                fields=["file", "shared_with"], name="file_shares_file_id_d49bb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileshare",
            index=models.Index(
                fields=["share_token"], name="file_shares_share_t_68bcb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileshare",
            index=models.Index(
                fields=["expires_at"], name="file_shares_expires_1bc2a0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fileshare",
            unique_together={("file", "shared_with")},
        ),
    ]
