# Generated by Django 4.2.16 on 2025-12-25 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userfile",
            name="user_files_task_id_195325_idx",
        ),
        migrations.RemoveField(
            model_name="userfile",
            name="task",
        ),
    ]
